openapi: 3.0.3
info:
  title: API de banco para realizar operações de conta
  description: |-
    API de banco que realiza as seguintes operações:
    - criar conta
    - deletar conta
    - buscar conta
    -
    - depositar um valor na conta
    - sacar um valor da conta

  version: 1.0-SNAPSHOT
servers:
  - url: https://testenvironment.org/api/v1
  - url: https://prodenvironment.org/api/v1
tags:
  - name: accounts
    description: Operações de contas bancárias
paths:
  /account:
    get:
      tags:
        - accounts
      summary: buscar todas as contas
      description: devolve uma lista com todas as contas no sistema
      operationId: getAccount
      responses:
        200:
          description: Successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        404:
          description: conta nao encontrada
          content:
            application/json:
              schema:
                 $ref: '#/components/schemas/ErrorResponse'

  /account/deposit:
    post:
      tags:
        - accounts
      summary: Depositar quantia na conta
      description: Iniciar operação de deposito em uma conta especifica
      operationId: depositToAccount
      requestBody:
        description: Numero da conta e valor a depositar
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositRequest'
        required: true
      responses:
        204:
          description: Successo
        404:
          description: conta nao encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /account/withdraw:
    post:
      tags:
        - accounts
      summary: sacar uma quantia
      description: executar uma operaçao de saque a partir do número da conta
      operationId: withdrawToAccount
      requestBody:
        description: numero da conta e valor para sacar
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawRequest'
        required: true
      responses:
        204:
          description: saque realizado
        400:
          description: informações invalidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: conta nao encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /account/create:
    post:
      tags:
        - accounts
      summary: Criar nova conta
      description: criar uma nova conta no banco
      operationId: createAccount
      requestBody:
        description: Dados para criaçao da conta
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      responses:
        201:
          description: conta criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        400:
          description: informaçoes invalidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /account/{accountNumber}:
    delete:
      tags:
        - accounts
      summary: deletar conta
      description: Deletar a conta do banco a partir do numero da conta
      operationId: deleteAccount
      parameters:
        - name: accountNumber
          in: path
          required: true
          description: numero da conta para deletar
          schema:
            type: string
      responses:
        204:
          description: conta deletada com sucesso
        400:
          description: dados invalidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Conta inexistente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Account:
      type: object
      properties:
        accountNumber:
          type: string
        balance:
          type: integer
    DepositRequest:
      type: object
      properties:
        accountNumber:
          type: string
        depositAmount:
          type: integer
    WithdrawRequest:
      type: object
      properties:
        accountNumber:
          type: string
        withdrawAmount:
          type: integer
    ErrorResponse:
      type: object
      properties:
        message:
          type: string